# Configure codecov.
# https://docs.codecov.io/docs/codecov-yaml

# If Codecov fails to find "previous" commit to compare to, consider it
# a success.  This has its own problems and is not ideal.  However,
# without this, recovering from previous test failures
# can be painful & misleading.  Per:
# https://github.com/codecov/support/issues/173
coverage:
  status:
    project:
      default:
        target: auto  # this is default
        if_not_found: success  # no commit found? still set a success
